// Структура пробного ҰБТ: 3 обязательных предмета + 2 профильных,
// которые подставляются автоматически по выбранной специальности (коду).

export const ENT_MANDATORY = [
  { id: "history", name: "Қазақстан тарихы" },
  { id: "mathlit", name: "Математикалық сауаттылық" },
  { id: "readlit", name: "Оқу сауаттылығы" },
];
export const ENT_MANDATORY_IDS = ENT_MANDATORY.map((s) => s.id);

// Все предметы (id → название + иконка)
export const SUBJECTS: Record<string, { name: string; icon: string }> = {
  history: { name: "Қазақстан тарихы", icon: "🏛️" },
  mathlit: { name: "Математикалық сауаттылық", icon: "🔢" },
  readlit: { name: "Оқу сауаттылығы", icon: "📖" },
  math: { name: "Математика", icon: "📐" },
  physics: { name: "Физика", icon: "⚛️" },
  chemistry: { name: "Химия", icon: "🧪" },
  biology: { name: "Биология", icon: "🧬" },
  geography: { name: "География", icon: "🌍" },
  informatics: { name: "Информатика", icon: "💻" },
  worldhistory: { name: "Дүниежүзі тарихы", icon: "🌐" },
  foreign: { name: "Шетел тілі", icon: "🔤" },
  kazlang: { name: "Қазақ тілі", icon: "🇰🇿" },
  kazlit: { name: "Қазақ әдебиеті", icon: "📚" },
  ruslang: { name: "Орыс тілі", icon: "🇷🇺" },
  ruslit: { name: "Орыс әдебиеті", icon: "📕" },
  law: { name: "Құқық негіздері", icon: "⚖️" },
  creative: { name: "Шығармашылық емтихан", icon: "🎨" },
};

export const subjectName = (id?: string | null) => (id ? SUBJECTS[id]?.name ?? id : "");
export const subjectIcon = (id?: string | null) => (id ? SUBJECTS[id]?.icon ?? "📘" : "📘");

// Список предметов для выбора в админке (без творческого)
export const ALL_SUBJECTS = Object.entries(SUBJECTS)
  .filter(([id]) => id !== "creative")
  .map(([id, v]) => ({ id, name: v.name }));

// Профильные предметы (без 3 обязательных и творческого) — для главной страницы
export const ENT_PROFILE_IDS = [
  "math", "physics", "chemistry", "biology", "informatics",
  "geography", "worldhistory", "foreign", "kazlang", "kazlit",
  "ruslang", "ruslit", "law",
];
export const ENT_PROFILE_SUBJECTS = ENT_PROFILE_IDS.map((id) => ({
  id,
  name: SUBJECTS[id].name,
  icon: SUBJECTS[id].icon,
}));

export type Specialty = { code: string; name: string; subjects: [string, string] };

// Полный список групп образовательных программ ҰБТ (профильные предметы)
export const SPECIALTIES: Specialty[] = [
  { code: "B001", name: "Педагогика и психология", subjects: ["biology", "geography"] },
  { code: "B002", name: "Дошкольное обучение и воспитание", subjects: ["biology", "geography"] },
  { code: "B003", name: "Педагогика и методика начального обучения", subjects: ["biology", "geography"] },
  { code: "B004", name: "Подготовка учителей начальной военной подготовки", subjects: ["creative", "creative"] },
  { code: "B005", name: "Подготовка учителей физической культуры", subjects: ["creative", "creative"] },
  { code: "B006", name: "Подготовка учителей музыки", subjects: ["creative", "creative"] },
  { code: "B007", name: "Подготовка учителей художественного труда и черчения", subjects: ["creative", "creative"] },
  { code: "B008", name: "Подготовка учителей основы права и экономики", subjects: ["worldhistory", "geography"] },
  { code: "B009", name: "Подготовка учителей математики", subjects: ["math", "physics"] },
  { code: "B010", name: "Подготовка учителей физики", subjects: ["physics", "math"] },
  { code: "B011", name: "Подготовка учителей информатики", subjects: ["math", "informatics"] },
  { code: "B012", name: "Подготовка учителей химии", subjects: ["chemistry", "biology"] },
  { code: "B013", name: "Подготовка учителей биологии", subjects: ["biology", "chemistry"] },
  { code: "B014", name: "Подготовка учителей географии", subjects: ["geography", "worldhistory"] },
  { code: "B015", name: "Подготовка учителей по гуманитарным предметам", subjects: ["worldhistory", "geography"] },
  { code: "B016", name: "Подготовка учителей казахского языка и литературы", subjects: ["kazlang", "kazlit"] },
  { code: "B017", name: "Подготовка учителей русского языка и литературы", subjects: ["ruslang", "ruslit"] },
  { code: "B018", name: "Подготовка учителей иностранного языка", subjects: ["foreign", "worldhistory"] },
  { code: "B019", name: "Подготовка социальных педагогов", subjects: ["biology", "geography"] },
  { code: "B020", name: "Специальная педагогика", subjects: ["biology", "geography"] },
  { code: "B120", name: "Подготовка педагогов профессионального обучения", subjects: ["physics", "math"] },
  { code: "B021", name: "Исполнительское искусство", subjects: ["creative", "creative"] },
  { code: "B022", name: "Музыковедение", subjects: ["creative", "creative"] },
  { code: "B023", name: "Режиссура, арт-менеджмент", subjects: ["creative", "creative"] },
  { code: "B024", name: "Искусствоведение", subjects: ["creative", "creative"] },
  { code: "B025", name: "Дирижирование", subjects: ["creative", "creative"] },
  { code: "B026", name: "Композиция", subjects: ["creative", "creative"] },
  { code: "B027", name: "Театральное искусство", subjects: ["creative", "creative"] },
  { code: "B028", name: "Хореография", subjects: ["creative", "creative"] },
  { code: "B029", name: "Аудиовизуальные средства и медиа производство", subjects: ["creative", "creative"] },
  { code: "B030", name: "Изобразительное искусство", subjects: ["creative", "creative"] },
  { code: "B031", name: "Мода, дизайн", subjects: ["creative", "creative"] },
  { code: "B099", name: "Инструментальное исполнительство", subjects: ["creative", "creative"] },
  { code: "B100", name: "Вокальное искусство", subjects: ["creative", "creative"] },
  { code: "B101", name: "Традиционное музыкальное искусство", subjects: ["creative", "creative"] },
  { code: "B102", name: "Искусство эстрады", subjects: ["creative", "creative"] },
  { code: "B103", name: "Режиссура кино и ТВ", subjects: ["creative", "creative"] },
  { code: "B104", name: "Режиссура сценических искусств и цирка", subjects: ["creative", "creative"] },
  { code: "B105", name: "Режиссура анимации", subjects: ["creative", "creative"] },
  { code: "B106", name: "Операторское и фото искусство", subjects: ["creative", "creative"] },
  { code: "B107", name: "Медиаискусство и цифровые технологии", subjects: ["creative", "creative"] },
  { code: "B108", name: "Сценография", subjects: ["creative", "creative"] },
  { code: "B109", name: "Декоративное искусство", subjects: ["creative", "creative"] },
  { code: "B110", name: "Фэшн дизайн", subjects: ["creative", "creative"] },
  { code: "B032", name: "Философия и этика", subjects: ["worldhistory", "geography"] },
  { code: "B033", name: "Религия и теология", subjects: ["creative", "creative"] },
  { code: "B034", name: "История", subjects: ["worldhistory", "geography"] },
  { code: "B134", name: "Археология и этнология", subjects: ["worldhistory", "geography"] },
  { code: "B035", name: "Тюркология", subjects: ["worldhistory", "foreign"] },
  { code: "B135", name: "Востоковедение", subjects: ["worldhistory", "foreign"] },
  { code: "B036", name: "Переводческое дело", subjects: ["foreign", "worldhistory"] },
  { code: "B037", name: "Филология", subjects: ["kazlang", "kazlit"] },
  { code: "B038", name: "Социология", subjects: ["math", "geography"] },
  { code: "B039", name: "Культурология", subjects: ["worldhistory", "foreign"] },
  { code: "B040", name: "Политология", subjects: ["worldhistory", "foreign"] },
  { code: "B140", name: "Международные отношения и дипломатия", subjects: ["worldhistory", "foreign"] },
  { code: "B041", name: "Психология", subjects: ["biology", "geography"] },
  { code: "B042", name: "Журналистика и репортерское дело", subjects: ["creative", "creative"] },
  { code: "B043", name: "Библиотечное дело, обработка информации и архивное дело", subjects: ["kazlang", "kazlit"] },
  { code: "B044", name: "Менеджмент и управление", subjects: ["math", "geography"] },
  { code: "B045", name: "Аудит и налогообложение", subjects: ["math", "geography"] },
  { code: "B145", name: "Государственный аудит", subjects: ["math", "geography"] },
  { code: "B046", name: "Финансы, экономика, банковское и страховое дело", subjects: ["math", "geography"] },
  { code: "B047", name: "Маркетинг и реклама", subjects: ["math", "geography"] },
  { code: "B048", name: "Трудовые навыки", subjects: ["math", "geography"] },
  { code: "B049", name: "Право", subjects: ["worldhistory", "law"] },
  { code: "B050", name: "Биологические и смежные науки", subjects: ["biology", "chemistry"] },
  { code: "B051", name: "Окружающая среда", subjects: ["biology", "geography"] },
  { code: "B052", name: "Наука о земле", subjects: ["math", "geography"] },
  { code: "B053", name: "Химия", subjects: ["chemistry", "biology"] },
  { code: "B054", name: "Физика", subjects: ["physics", "math"] },
  { code: "B055", name: "Математика и статистика", subjects: ["math", "physics"] },
  { code: "B056", name: "Механика", subjects: ["math", "physics"] },
  { code: "B057", name: "Информационные технологии", subjects: ["math", "informatics"] },
  { code: "B058", name: "Информационная безопасность", subjects: ["math", "informatics"] },
  { code: "B158", name: "Криптология", subjects: ["math", "informatics"] },
  { code: "B059", name: "Коммуникации и коммуникационные технологии", subjects: ["math", "physics"] },
  { code: "B060", name: "Химическая инженерия и процессы", subjects: ["chemistry", "physics"] },
  { code: "B061", name: "Материаловедение и технологии", subjects: ["math", "physics"] },
  { code: "B062", name: "Электротехника и энергетика", subjects: ["math", "physics"] },
  { code: "B063", name: "Электротехника и автоматизация", subjects: ["math", "physics"] },
  { code: "B064", name: "Механика и металлообработка", subjects: ["math", "physics"] },
  { code: "B065", name: "Транспортная техника и технологии", subjects: ["math", "physics"] },
  { code: "B066", name: "Морской транспорт и технологии", subjects: ["math", "physics"] },
  { code: "B067", name: "Воздушный транспорт и технологии", subjects: ["math", "physics"] },
  { code: "B167", name: "Летная эксплуатация летательных аппаратов", subjects: ["math", "physics"] },
  { code: "B165", name: "Магистральные сети и инфраструктура", subjects: ["math", "physics"] },
  { code: "B166", name: "Транспортные сооружения", subjects: ["math", "physics"] },
  { code: "B068", name: "Производство продуктов питания", subjects: ["biology", "chemistry"] },
  { code: "B069", name: "Производство материалов (стекло, бумага, пластик, дерево)", subjects: ["math", "physics"] },
  { code: "B070", name: "Текстиль: одежда, обувь и кожаные изделия", subjects: ["math", "physics"] },
  { code: "B071", name: "Горное дело и добыча полезных ископаемых", subjects: ["math", "physics"] },
  { code: "B072", name: "Технология фармацевтического производства", subjects: ["chemistry", "biology"] },
  { code: "B073", name: "Архитектура", subjects: ["creative", "creative"] },
  { code: "B173", name: "Гидромелиорация", subjects: ["math", "physics"] },
  { code: "B175", name: "Водоснабжение и водоотведение", subjects: ["math", "physics"] },
  { code: "B074", name: "Градостроительство и гражданское строительство", subjects: ["math", "physics"] },
  { code: "B126", name: "Транспортное строительство", subjects: ["math", "physics"] },
  { code: "B176", name: "Гидротехническое строительство", subjects: ["math", "physics"] },
  { code: "B075", name: "Кадастр и землеустройство", subjects: ["math", "geography"] },
  { code: "B076", name: "Стандартизация, сертификация и метрология", subjects: ["math", "physics"] },
  { code: "B077", name: "Растениеводство", subjects: ["biology", "chemistry"] },
  { code: "B078", name: "Животноводство", subjects: ["biology", "chemistry"] },
  { code: "B079", name: "Лесное хозяйство", subjects: ["biology", "geography"] },
  { code: "B080", name: "Рыбное хозяйство", subjects: ["biology", "chemistry"] },
  { code: "B081", name: "Землеустройство", subjects: ["math", "physics"] },
  { code: "B082", name: "Водные ресурсы и водопользования", subjects: ["math", "physics"] },
  { code: "B183", name: "Агроинженерия", subjects: ["math", "physics"] },
  { code: "B083", name: "Ветеринария", subjects: ["biology", "chemistry"] },
  { code: "B091", name: "Туризм", subjects: ["geography", "foreign"] },
  { code: "B092", name: "Досуг", subjects: ["creative", "creative"] },
  { code: "B093", name: "Ресторанное дело и гостиничный бизнес", subjects: ["geography", "foreign"] },
  { code: "B094", name: "Санитарно-профилактические мероприятия", subjects: ["math", "physics"] },
  { code: "B095", name: "Транспортные услуги", subjects: ["math", "geography"] },
  { code: "B090", name: "Социальная работа", subjects: ["biology", "geography"] },
  { code: "B098", name: "Спорт", subjects: ["creative", "creative"] },
  { code: "B084", name: "Сестринское дело", subjects: ["biology", "chemistry"] },
  { code: "B085", name: "Фармация", subjects: ["biology", "chemistry"] },
  { code: "BM086", name: "Медицина", subjects: ["biology", "chemistry"] },
  { code: "BM087", name: "Стоматология", subjects: ["biology", "chemistry"] },
  { code: "BM088", name: "Педиатрия", subjects: ["biology", "chemistry"] },
  { code: "B089", name: "Общественное здоровье", subjects: ["biology", "chemistry"] },
  { code: "BM089", name: "Медико-профилактическое дело", subjects: ["biology", "chemistry"] },
  { code: "B096", name: "Правоохранительная деятельность", subjects: ["worldhistory", "law"] },
  { code: "B097", name: "Пожарная безопасность", subjects: ["math", "physics"] },
];
